/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.cpp                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: lps <lps@student.42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/09/19 12:24:49 by lps               #+#    #+#             */
/*   Updated: 2024/09/21 16:59:57 by lps              ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "BitcoinExchange.hpp"

int main(int argc, const char** argv) {
	if (argc != 2)
	{
		std::cout << "Invalid Input: ./< file name >" << std::endl;
		 return (1);
	}
	try
	{
		BitcoinExchange b(argv[1]);
		BitcoinExchange a = BitcoinExchange(b);
		BitcoinExchange c = a;
		// c.printDatabase();
	}
	catch(const std::exception& e)
	{
		std::cout << e.what() << '\n';
	}
	return 0;
}


// BitcoinExchange b(argv[1]);

// The constructor of the BitcoinExchange class is called with argv[1] (the file name passed by the user) as an argument. It initializes the object b. Presumably, this object reads or processes data from the file.
// BitcoinExchange a = BitcoinExchange(b);

// This is creating a new object a by invoking the copy constructor of the BitcoinExchange class, explicitly copying the object b. The copy constructor is likely defined or implicitly generated by the compiler to duplicate the state of b into a.
// BitcoinExchange c = a;

// This is another object c being created, and it's a copy of a. Since a is already a copy of b, now both a and c are copies of b.